configure clean up jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -367,11 +367,40 @@ jobs:
               --tags project=udapeople
 
             echo "Current workflow ID: ${CIRCLE_WORKFLOW_ID:0:7}"
+            #save current workflow id in mem
+            curl -k https://kvdb.io/Mjins2pywh7XyGqhFKxNLM/uda-people-last_workflow  -d "${CIRCLE_WORKFLOW_ID:0:7}"
       - revert-migrations:
           migration_id: migration_${CIRCLE_WORKFLOW_ID:0:7}
       - destroy-environment:
           backend-name: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
           frontend-name: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+  
+  cleanup:
+    <<: *nodeMachine
+    steps:
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+      - run:
+          name: Remove old stacks and files
+          command: |
+            curl -k https://kvdb.io/Mjins2pywh7XyGqhFKxNLM/uda-people-last_workflow > res.txt
+            
+            if  grep -q "Not Found" res.txt
+            then
+              echo "not found"
+              exit 1
+            else
+              aws s3 rm "s3://udapeople-$(tail -1 res.txt)" --recursive
+              aws cloudformation delete-stack --stack-name "udapeople-backend-$(tail -1 res.txt)"
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-$(tail -1 res.txt)"
+              #delete workflow key.
+              curl -k https://kvdb.io/Mjins2pywh7XyGqhFKxNLM/uda-people-last_workflow -XDELETE
+            fi
 
 workflows:
   default:
@@ -402,3 +431,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
